var btnIcon = document.getElementById('btnIcon')
var btnVoltar = document.getElementById('btnVoltar')
var btnSobreMim = document.getElementById('btnSobreMim')
var btnContato = document.getElementById('btnContato')
var btnHabilidades = document.getElementById('btnHabilidades')
var btnProjetos = document.getElementById('btnProjetos')

btnIcon.onclick = function(){
    var menu = document.getElementById('menu')
    menu.style.left = '0px'
}
btnVoltar.onclick = function(){
    var menu = document.getElementById('menu')
    menu.style.left = '-300px'
}
btnSobreMim.onclick = function(){
    var SobreMim = document.getElementById('SobreMim')
    var Contato = document.getElementById('Contato')
    var Habilidades = document.getElementById('Habilidades')
    var Projetos = document.getElementById('Projetos')
    var btnCarrouseProjetos = document.getElementById('btnCarrouseProjetos')
    var menu = document.getElementById('menu')
    var Titulo = document.getElementById('Titulo')
    Titulo.innerHTML = '<h2>Sobre mim</h2>'
    Projetos.style.display = 'none'
    btnCarrouseProjetos.style.display = 'none'
    Contato.style.display = 'none'
    Habilidades.style.display = 'none'
    SobreMim.style.display = 'inline'
    menu.style.left = '-300px'
}
btnContato.onclick = function(){
    var SobreMim = document.getElementById('SobreMim')
    var Contato = document.getElementById('Contato')
    var Habilidades = document.getElementById('Habilidades')
    var Projetos = document.getElementById('Projetos')
    var btnCarrouseProjetos = document.getElementById('btnCarrouseProjetos')
    var menu = document.getElementById('menu')
    var Titulo = document.getElementById('Titulo')
    Titulo.innerHTML = '<h2>Contato</h2>'
    Projetos.style.display = 'none'
    btnCarrouseProjetos.style.display = 'none'
    Contato.style.display = 'inline'
    Habilidades.style.display = 'none'
    SobreMim.style.display = 'none'
    menu.style.left = '-300px'
}
btnHabilidades.onclick = function(){
    var SobreMim = document.getElementById('SobreMim')
    var Contato = document.getElementById('Contato')
    var Habilidades = document.getElementById('Habilidades')
    var Projetos = document.getElementById('Projetos')
    var btnCarrouseProjetos = document.getElementById('btnCarrouseProjetos')
    var menu = document.getElementById('menu')
    var Titulo = document.getElementById('Titulo')
    Titulo.innerHTML = '<h2>Habilidades</h2>'
    Projetos.style.display = 'none'
    btnCarrouseProjetos.style.display = 'none'
    Habilidades.style.display = 'inline'
    Contato.style.display = 'none'
    SobreMim.style.display = 'none'
    menu.style.left = '-300px'
}
btnProjetos.onclick = function(){
    var SobreMim = document.getElementById('SobreMim')
    var Contato = document.getElementById('Contato')
    var Habilidades = document.getElementById('Habilidades')
    var Projetos = document.getElementById('Projetos')
    var btnCarrouseProjetos = document.getElementById('btnCarrouseProjetos')
    var menu = document.getElementById('menu')
    var Titulo = document.getElementById('Titulo')
    Titulo.innerHTML = '<h2>Projetos</h2>'
    btnCarrouseProjetos.style.display = 'inline'
    Projetos.style.display = 'inline'
    Habilidades.style.display = 'none'
    Contato.style.display = 'none'
    SobreMim.style.display = 'none'
    menu.style.left = '-300px'
}